In [1]:
import pandas as pd
import numpy as np
import math
import time
import random
import re
from PIL import Image
import matplotlib.pyplot as plt
from cvxopt import matrix
from cvxopt import solvers
from libsvm.svmutil import *
from pathlib import Path
from sklearn.svm import *

In [2]:
class0 = list()
path0 = 'svm/train/0/'
for image in Path(path0).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    class0.append(image_resized)
label0 = np.array(class0) 

class1 = list()
path1 = 'svm/train/1/'
for image in Path(path1).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    class1.append(image_resized)
label1 = np.array(class1)

class2 = list()
path2 = 'svm/train/2/'
for image in Path(path2).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    class2.append(image_resized)
label2 = np.array(class2) 

class3 = list()
path3 = 'svm/train/3/'
for image in Path(path3).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    class3.append(image_resized)
label3 = np.array(class3) 

class4 = list()
path4 = 'svm/train/4/'
for image in Path(path4).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    class4.append(image_resized)
label4 = np.array(class4) 

class5 = list()
path5 = 'svm/train/5/'
for image in Path(path5).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    class5.append(image_resized)
label5 = np.array(class5) 

In [3]:
y0 = np.full((2380, 1), fill_value=0, dtype='double')
y1 = np.full((2380, 1), fill_value=1, dtype='double')
y2 = np.full((2380, 1), fill_value=2, dtype='double')
y3 = np.full((2380, 1), fill_value=3, dtype='double')
y4 = np.full((2380, 1), fill_value=4, dtype='double')
y5 = np.full((2380, 1), fill_value=5, dtype='double')

In [4]:
x_dict = {}
y_dict = {}

x_dict[0] = label0
x_dict[1] = label1
x_dict[2] = label2
x_dict[3] = label3
x_dict[4] = label4
x_dict[5] = label5

y_dict[0] = y0
y_dict[1] = y1
y_dict[2] = y2
y_dict[3] = y3
y_dict[4] = y4
y_dict[5] = y5

In [5]:
vclass0 = list()
vpath0 = 'svm/val/0/'
for image in Path(vpath0).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    vclass0.append(image_resized)
vlabel0 = np.array(vclass0) 

vclass1 = list()
vpath1 = 'svm/val/1/'
for image in Path(vpath1).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    vclass1.append(image_resized)
vlabel1 = np.array(vclass1)

vclass2 = list()
vpath2 = 'svm/val/2/'
for image in Path(vpath2).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    vclass2.append(image_resized)
vlabel2 = np.array(vclass2) 

vclass3 = list()
vpath3 = 'svm/val/3/'
for image in Path(vpath3).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    vclass3.append(image_resized)
vlabel3 = np.array(vclass3)

vclass4 = list()
vpath4 = 'svm/val/4/'
for image in Path(vpath4).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    vclass4.append(image_resized)
vlabel4 = np.array(vclass4) 

vclass5 = list()
vpath5 = 'svm/val/5/'
for image in Path(vpath5).glob('*.jpg'):
    image_resized = np.array(Image.open(image).resize((16, 16))).flatten()/255
    vclass5.append(image_resized)
vlabel5 = np.array(vclass5)

vy0 = np.full((vlabel0.shape[0], 1), fill_value=0, dtype='double')
vy1 = np.full((vlabel1.shape[0], 1), fill_value=1, dtype='double')
vy2 = np.full((vlabel2.shape[0], 1), fill_value=2, dtype='double')
vy3 = np.full((vlabel3.shape[0], 1), fill_value=3, dtype='double')
vy4 = np.full((vlabel4.shape[0], 1), fill_value=4, dtype='double')
vy5 = np.full((vlabel5.shape[0], 1), fill_value=5, dtype='double')

vx = np.concatenate((vlabel0, vlabel1))
vx = np.concatenate((vx, vlabel2))
vx = np.concatenate((vx, vlabel3))
vx = np.concatenate((vx, vlabel4))
vx = np.concatenate((vx, vlabel5))

vy = np.concatenate((vy0, vy1))
vy = np.concatenate((vy, vy2))
vy = np.concatenate((vy, vy3))
vy = np.concatenate((vy, vy4))
vy = np.concatenate((vy, vy5))


In [6]:
print(np.concatenate((x_dict[1], x_dict[0])))
print(np.concatenate((y_dict[3], y_dict[2])))

[[0.1372549  0.16078431 0.07843137 ... 0.3254902  0.44313725 0.17254902]
 [0.29803922 0.37647059 0.22745098 ... 0.34509804 0.28627451 0.17647059]
 [0.21176471 0.32156863 0.23921569 ... 0.30588235 0.30588235 0.25490196]
 ...
 [0.35686275 0.54901961 0.81960784 ... 0.27843137 0.41960784 0.18039216]
 [0.96078431 0.97647059 0.98823529 ... 0.27058824 0.24705882 0.23921569]
 [0.05098039 0.34901961 0.57254902 ... 0.24313725 0.23529412 0.25882353]]
[[3.]
 [3.]
 [3.]
 ...
 [2.]
 [2.]
 [2.]]


In [7]:
q = np.full((4760, 1), fill_value=-1, dtype='double')
c = 1
G = np.concatenate((np.identity(4760, dtype='double'), np.identity(4760, dtype='double')*(-1)))
h = np.concatenate((np.full((4760, 1), fill_value=c, dtype='double'), np.zeros((4760, 1), dtype='double')))
b = np.zeros((1,1), dtype='double')

In [8]:
def svm_cvxopt(x, y, label1, label2):
    for i in range(0, 4760):
        if(y[i][0]==label1):
            y[i][0]=-1
        else:
            y[i][0]=1

    P = np.empty((4760, 4760), dtype='double')
    gamma = 0.001
    for i in range(0, 4760):
        for j in range(0, 4760):
            P[i][j] = y[i][0]*y[j][0]*np.exp(-gamma * np.linalg.norm(np.asarray(x[i])-np.asarray(x[j])))
    A = y.reshape((1, 4760))

    sol = solvers.qp(matrix(P), matrix(q), matrix(G), matrix(h), matrix(A), matrix(b))
    optimal_alpha = np.array(sol['x'])
    alpha = np.where(optimal_alpha<0.0001, 0, optimal_alpha)

    temp = np.empty((4760, 4760))
    for i in range(0, 4760):
        for j in range(0, 4760):
            temp[i][j] = alpha[i][0]*y[i][0]*np.exp(-gamma * np.linalg.norm(np.asarray(x[i])-np.asarray(x[j])))
    train_wTx = np.asarray(np.sum(temp, axis=0))

    all_b = train_wTx.reshape((4760, 1))
    b_opt = -0.5*(np.max(all_b[np.where(y==-1) and np.where(alpha!=0)], axis=0) + np.min(all_b[np.where(y==1) and np.where(alpha!=0)], axis=0))

    vtemp = np.empty((x.shape[0], vx.shape[0]))
    for i in range(0, x.shape[0]):
        for j in range(0, vx.shape[0]):
            vtemp[i][j] = alpha[i][0]*y[i][0]*np.exp(-gamma * np.linalg.norm(np.asarray(x[i])-np.asarray(vx[j])))
    valid_wTx = np.asarray(np.sum(vtemp, axis=0))

    y_pred = list()
    for i in range(0, vy.shape[0]):
        val = label2 if(valid_wTx[i] + b_opt)>0 else label1
        y_pred.append(int(val))

    return np.array(y_pred, dtype='int').reshape((1200,))


In [9]:
y_pred_cvxopt = np.empty((6, 6, 1200), dtype='int')

for i in range(0, 6):
    for j in range(0, i):
        y_pred_cvxopt[i][j] = svm_cvxopt(np.concatenate((x_dict[i], x_dict[j])), np.concatenate((y_dict[i], y_dict[j])), i, j)

     pcost       dcost       gap    pres   dres
 0: -2.3494e+03 -1.3356e+04  6e+04  3e+00  1e-12
 1: -1.6273e+03 -9.1778e+03  8e+03  2e-12  1e-12
 2: -1.9247e+03 -2.9406e+03  1e+03  3e-12  1e-12
 3: -2.2161e+03 -2.4992e+03  3e+02  4e-12  1e-12
 4: -2.2792e+03 -2.4301e+03  2e+02  8e-13  1e-12
 5: -2.3224e+03 -2.3755e+03  5e+01  3e-12  1e-12
 6: -2.3384e+03 -2.3560e+03  2e+01  2e-12  1e-12
 7: -2.3453e+03 -2.3479e+03  3e+00  1e-12  1e-12
 8: -2.3464e+03 -2.3466e+03  2e-01  4e-12  1e-12
 9: -2.3465e+03 -2.3465e+03  6e-03  2e-12  1e-12
10: -2.3465e+03 -2.3465e+03  1e-04  7e-13  1e-12
Optimal solution found.
     pcost       dcost       gap    pres   dres
 0: -3.5464e+03 -1.2189e+04  4e+04  2e+00  1e-12
 1: -2.6772e+03 -8.3096e+03  6e+03  6e-13  2e-12
 2: -3.1282e+03 -3.7725e+03  6e+02  1e-12  1e-12
 3: -3.4090e+03 -3.5725e+03  2e+02  3e-12  2e-12
 4: -3.4817e+03 -3.5204e+03  4e+01  1e-12  2e-12
 5: -3.4979e+03 -3.5077e+03  1e+01  2e-12  2e-12
 6: -3.5024e+03 -3.5042e+03  2e+00  5e-14  2e-1

In [10]:
for i in range(0, 6):
    for j in range(0, i):
        print(y_pred_cvxopt[i][j])

[0 0 1 ... 1 0 1]
[0 2 0 ... 0 0 0]
[2 2 1 ... 1 2 1]
[3 0 0 ... 0 0 0]
[3 1 1 ... 1 3 1]
[3 2 2 ... 3 3 3]
[0 0 4 ... 0 0 0]
[4 4 1 ... 1 1 1]
[4 2 4 ... 4 4 4]
[3 4 4 ... 4 3 4]
[0 5 5 ... 5 5 0]
[1 5 1 ... 1 5 1]
[2 2 5 ... 5 5 5]
[3 5 5 ... 5 5 5]
[4 5 5 ... 5 5 5]


In [11]:
for i in range(0, 1200):
    print(y_pred_cvxopt[2][0][i])

0
2
0
2
0
0
2
2
2
0
0
0
0
0
2
2
2
0
0
2
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
2
2
2
0
2
0
0
0
0
0
2
0
2
0
0
0
0
0
0
0
2
0
0
0
0
0
2
0
0
0
2
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
2
0
0
0
0
0
0
0
0
0
2
0
0
2
2
0
2
0
0
2
2
2
0
0
2
0
0
0
2
0
0
0
0
2
0
0
0
2
0
2
2
0
0
0
0
0
2
0
0
0
0
2
0
2
2
0
0
0
0
2
0
0
0
0
2
0
2
0
2
2
0
2
2
2
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
2
0
2
2
0
2
0
0
0
2
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
2
0
0
0
0
0
0
0
2
0
0
2
0
2
0
2
2
2
0
2
2
0
2
2
2
2
0
2
0
0
2
2
2
2
2
2
2
0
0
2
2
2
0
2
2
2
2
2
2
2
2
2
2
2
0
2
2
2
2
2
0
2
0
2
2
2
2
2
2
0
2
2
0
0
2
2
2
2
2
2
2
2
2
2
2
2
2
2
0
0
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2


In [12]:
y_pred_cvxopt_final = list()

for k in range(0, 1200):
    temp = [0, 0, 0, 0, 0, 0]
    for i in range(0, 6):
        for j in range(0, i):
            ind = int(y_pred_cvxopt[i][j][k])
            temp[ind] += 1
    y_pred_cvxopt_final.append(np.array(temp).argmax())

count_cvxopt = 0
for i in range(0, vy.shape[0]):
    if(y_pred_cvxopt_final[i] == vy[i]):
        count_cvxopt += 1
print(count_cvxopt/len(y_pred_cvxopt_final))

0.47833333333333333


In [13]:
def svm_svc(x, y, label1, label2):
    guassian_model = SVC(kernel='rbf', C=1.0, gamma=0.001)
    guassian_model.fit(x, y)
    return np.array(guassian_model.predict(vx)).reshape((1200,))

In [14]:
y_pred_svc = np.empty((6, 6, 1200))

for i in range(0, 6):
    for j in range(0, i):
        y_pred_svc[i][j] = svm_svc(np.concatenate((x_dict[i], x_dict[j])), np.concatenate((y_dict[i], y_dict[j])), i, j)

c:\Users\samra\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\samra\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\samra\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\samra\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1183: DataC

In [15]:
y_pred_svc_final = list()

for k in range(0, 1200):
    temp = [0, 0, 0, 0, 0, 0]
    for i in range(0, 6):
        for j in range(0, i):
            ind = int(y_pred_svc[i][j][k])
            temp[ind] += 1
    y_pred_svc_final.append(np.array(temp).argmax())

count_svc = 0
for i in range(0, vy.shape[0]):
    if(y_pred_svc_final[i] == vy[i]):
        count_svc += 1
print(count_svc/len(y_pred_svc_final))

0.5608333333333333


In [16]:
def confusion_matrix(prediction):
    conf_mat = list()

    for k in range(0, 6):
        temp = [0, 0, 0, 0, 0, 0]    
        for i in range(k*200, (k+1)*200):
            temp[prediction[i]] += 1
        conf_mat.append(temp)

    return conf_mat

In [17]:
print(confusion_matrix(y_pred_cvxopt_final))

[[39, 45, 33, 42, 23, 18], [2, 171, 4, 8, 5, 10], [5, 10, 119, 36, 23, 7], [14, 16, 23, 125, 16, 6], [9, 29, 65, 46, 46, 5], [16, 61, 22, 18, 9, 74]]


In [18]:
print(confusion_matrix(y_pred_svc_final))

[[79, 21, 22, 24, 23, 31], [6, 154, 1, 5, 10, 24], [8, 4, 130, 25, 21, 12], [26, 6, 24, 128, 12, 4], [26, 16, 58, 36, 58, 6], [22, 23, 12, 7, 12, 124]]
